version: 0.0
os: linux
files:
  - source: app.zip
    destination: /opt/app/releases
hooks:
  BeforeInstall:
    - location: scripts/unzip_and_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
